### ISSUE TITLE
Use Apache commons' ReflectionToStringBuilder

### ISSUE THREAD

**Issue by krichter722** [mjsax/aeolus#6]
Use [Apache commons' ReflectionToStringBuilder](http://commons.apache.org/proper/commons-lang//apidocs/org/apache/commons/lang3/builder/ReflectionToStringBuilder.html) in order to avoid the rather annoying construction and even more annoying changes (including field name refactoring) in `toString` methods.

**Comment by mjsax** [comment]
Spout/Bolts don't need toString() method -- can be removed
less dependencies are prevarable -- so stick with straight forward implemenation of toString if method is required
